### ISSUE TITLE
Magic cobble Gen issue

### ISSUE THREAD

**Issue by Ganome** [tastybento/ASkyBlock-Bugs-N-Features#164]
I cant get the magicgenerator to enable.  a blerp of my config:"
```
usemagiccobblegen: true
   
   # If set to true, Magic Cobblestone Generator will only work at spawn
   # Beware! Spawn MUST be in the same world that islands to work.
   magiccobblegenonlyatspawn: false
   
   # This won't be considered if usemagiccobblegen is set to false.
   # You can add, remove a block or modify its probability to be generated.
   # You can also set different probabilities from specified minimum levels
   magiccobblegenchances:
     #These probabilities will apply by default
     default:
       STONE: 85.0
       SANDSTONE: 10.0
       COAL_ORE: 2.0
       IRON_ORE: 2.0
       REDSTONE_ORE: 1.0
     #These probabilities will apply if island level is higher than 500.
     10:
       STONE: 80.0
       SANDSTONE: 10.0
       COAL_ORE: 5.0
       IRON_ORE: 2.0
       REDSTONE_ORE: 1.0
       GOLD_ORE: 1.0
       DIAMOND_ORE: 1.0
     15:
       STONE: 70.0
       SANDSTONE: 5.0
       COAL_ORE: 10.0
       IRON_ORE: 5.0
       REDSTONE_ORE: 5.0
       GOLD_ORE: 3.0
       DIAMOND_ORE: 2.0    
     20:
       STONE: 65.0
       SANDSTONE: 5.0
       COAL_ORE: 10.0
       IRON_ORE: 10.0
       REDSTONE_ORE: 5.0
       GOLD_ORE: 3.0
       DIAMOND_ORE: 2.0
     25:
       STONE: 60.0
       SANDSTONE: 5.0
       COAL_ORE: 10.0
       IRON_ORE: 10.0
       REDSTONE_ORE: 8.0
       GOLD_ORE: 4.0
       DIAMOND_ORE: 3.0    " END QUOTE
```

when i run the command "/asadmin cobblestats" it returns "none"

the closest thing to a version i can find is 
"-Generated by Maven
-Mon Apr 24 19:16:07 PDT 2017
version=3.0.6.3
groupId=com.wasteofplastic
artifactId=askyblock"

how can i fix the magic cobble generator?

EDIT: removed all pound signs and replaced with hyphens
