### ISSUE TITLE
acidisland.island.* permission

### ISSUE THREAD

**Issue by sZerz** [tastybento/ASkyBlock-Bugs-N-Features#196]
hello i have added to default group acidisland.island.* perm but it does give nothing

**Comment by Poslovitch** [comment]
What happens exactly?
What version are you using?
What do you think should happen?

**Comment by sZerz** [comment]
I still says that I have no permissions to use commands
Spigot 1.9 acidisland latest version from spigotmc

**Comment by tastybento** [comment]
First, you should not need to give acidisland.island.* to have the plugin work. The default permissions will enable it to work as is.

What is the exact error you see?

Are you using pex? What do you see if you do /pex group default list?

**Comment by sZerz** [comment]
but players can not use these default commands
I do not see any errors in console
my Pex groups

```
groups:
  Guest
    default: true
    build: true
    prefix: '&f'
    permissions
    - essentials.help
    - modifyworld.chat
    - modifyworld.*
    - essentials.home
    - essentials.sethome
    - essentials.back
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.spawn
    - essentials.spawn
    - acidisland.island.*
  Donor:
    build: true
    inheritance:
    - Guest
    prefix: '&6[Donor]&f'
    permissions:
    - essentials.enchant
    - essentials.repair
    - acidisland.craft.*
  Moderator:
    build: true
    inheritance:
    - Donor
    prefix: '&b[Moderator]&7'
    suffix: '&7'
    permissions:
    - essentials.repair
    - essentials.heal
    - essentials.item
    - essentials.give
    - essentials.fly
    - essentials.kick
    - essentials.mute
    - essentials.tjail
    - essentials.jail
    - essentials.tempban
    - essentials.vanish
    - acidisland.mod.*
  Owner:
    build:true
    inheritance:
    - Moderator
    prefix: '&4[Owner]'
    suffix: '&b'
    permissions:
    - '*'
```
