### ISSUE TITLE
Suspicious Lines located in Localization File 

### ISSUE THREAD

**Issue by DuckSoft** [tastybento/ASkyBlock-Bugs-N-Features#323]
## Problem
Visit the file [here](https://github.com/tastybento/askyblock/blob/a6be9549ab61a0e1fb105be25f1db9c31135b3bd/locale/zh-CN.yml#L139).
```yaml
ban: 
ban: 
  alreadybanned: "§e[name]§c早就列入了黑名单!"
  banned: "§c你被列入§e[name]§c的岛屿的黑名单!"
  fail: "§e[name]§c无法被列入黑名单!"
```
You see, there are **two `ban:` lines**!  

## Question
Are they both necessary?
