### ISSUE TITLE
Creeper bug + Companion mob bug

### ISSUE THREAD

**Issue by FrankHeijden** [tastybento/ASkyBlock-Bugs-N-Features#354]
Creepers are not damaging other entities on the island. these settings regarding creepers:

```
island:
   allowcreeperdamage: false
   allowcreepergriefing: false
   allowchestdamage: false

   world:
     CREEPER_PAIN: true
```

Also the companion (mob you start your island with) is not pushable.

all these things are tested on an empty server with only vault and askyblock
