### ISSUE TITLE
PvP doesnt work at spawn with invincible visitors

### ISSUE THREAD

**Issue by FrankHeijden** [tastybento/ASkyBlock-Bugs-N-Features#425]
PvP setting in `/is settings` at an `/asadmin setspawn` does not work. Tested on a clean paperspigot server, Paper version git-Paper-1188 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT), Vault 1.5.6-b49, ASkyBlock 3.0.7. PvP does work at players' islands.

Config settings tested with:
```
protection:
   world:
     ACID_DAMAGE: false
     ANVIL: true
     ARMOR_STAND: false
     BEACON: false
     BED: false
     BREAK_BLOCKS: false
     BREEDING: false
     BREWING: false
     BUCKET: false
     COLLECT_LAVA: false
     COLLECT_WATER: false
     CHEST: false
     CHORUS_FRUIT: false
     CRAFTING: true
     CREEPER_PAIN: true
     CROP_TRAMPLE: false
     DOOR: true
     EGGS: false
     ENCHANTING: true
     ENDER_PEARL: false
     ENTER_EXIT_MESSAGES: true
     FIRE: false
     FIRE_EXTINGUISH: false
     FIRE_SPREAD: false
     FURNACE: false
     GATE: false  
     HORSE_INVENTORY: false
     HORSE_RIDING: false
     HURT_MOBS: false
     HURT_MONSTERS: true
     LEASH: false
     LEVER_BUTTON: true
     MILKING: false
     MOB_SPAWN: true
     MONSTER_SPAWN: true
     MUSIC: false
     NETHER_PVP: true
     PLACE_BLOCKS: false
     PORTAL: true
     PRESSURE_PLATE: true
     PVP: true
     REDSTONE: false
     SPAWN_EGGS: false
     SHEARING: false
     VILLAGER_TRADING: true
     VISITOR_ITEM_DROP: true
     VISITOR_ITEM_PICKUP: true
   island:
     ACID_DAMAGE: false
     ANVIL: false
     ARMOR_STAND: false
     BEACON: false
     BED: false
     BREAK_BLOCKS: false
     BREEDING: false
     BREWING: false
     CHEST: false
     CHORUS_FRUIT: false
     CRAFTING: true
     CROP_TRAMPLE: false
     DOOR: false
     EGGS: false
     ENCHANTING: true
     ENDER_PEARL: false
     FIRE: false
     FIRE_EXTINGUISH: false
     FURNACE: false
     GATE: false   
     HORSE_INVENTORY: false
     HORSE_RIDING: false
     HURT_MOBS: false
     LEASH: false
     LEVER_BUTTON: false
     MILKING: false
     MUSIC: false
     PLACE_BLOCKS: false
     PORTAL: false
     PRESSURE_PLATE: false
     REDSTONE: false
     SPAWN_EGGS: false
     SHEARING: false
     VILLAGER_TRADING: false
     VISITOR_ITEM_DROP: false
     VISITOR_ITEM_PICKUP: false
```
