### ISSUE TITLE
"island" type challenges don't have in mind item durabilities

### ISSUE THREAD

**Issue by Zaino60** [tastybento/ASkyBlock-Bugs-N-Features#488]
I made a challenge that requires a specific type of prismarine block placed in your island (dark prismarine, item ID 168:2). However, the plugin doesn't recognizes the item sub-ids or durabilities and thinks it's 2 prismarine blocks instead of 32 blocks of 168:2. Same case with sponge, it thinks 1 sponge is needed instead of 2 wet sponges (19:1). Here's the example challenge for more info

``` 
aquarium:
      friendlyname: '&aPrimarina Aquarium'
      description: '&a➝ &6Objective: Construct a &bSmall Aquarium|&6Made out of 64 Prismarine, 32 Dark Prismarine,|&68 Sea Lanters and 2 Wet Sponges'
      level: 'Builder'
      type: island
      searchRadius: 50
      requiredItems: 'PRISMARINE:64 PRISMARINE:2:32 SEA_LANTERN:8 SPONGE:1:2'
      icon: 169
      takeItems: false
      rewardText: 128 raw fish, 2 guardian spawn eggs
      itemReward: 'RAW_FISH:128 MONSTER_EGG:GUARDIAN:2'
      moneyReward: 40
      expReward: 40
```

How to reproduce:
1- Add that challenge to your challenges.yml
2- Notice how you only require 2 prismarine blocks, 8 sea lanterns and 1 sponge to completed instead of the actual required blocks
