### ISSUE TITLE
Default island settings not set by settingsreset

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#502]
There are two settings, one for world, one for island. E.g.

```
world:
   # Allow furnace use
   FURNACE: true
island:
   # Allow visitor furnace use
   FURNACE: false
```

When the admin command settingsreset is used, only the world value is pushed to all islands, not the island value. The island keeps their old setting. The only way to change an island setting is by changing the world setting (then maybe changing it back).
