### ISSUE TITLE
Alchemist challenge can be done with water potions

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#506]
I can complete the challenge with 8 water bottle. But requiredItems are different potions. Here the challenge:

```
alchemist:
      friendlyname: 'Alchemist'
      description: 'Brew 1 potion of Fire Resistance, Slowness, Swiftness, Healing, Harming, Invisibility, Strength and Regeneration'
      icon: BREWING_STAND_ITEM
      level: 'Advanced'
      type: inventory
      requiredItems: 'POTION:FIRE_RESISTANCE::::1 POTION:SLOWNESS::::1 POTION:SPEED::::1 POTION:INSTANT_HEAL::::1 POTION:INSTANT_DAMAGE::::1 POTION:INVISIBILITY::::1 POTION:STRENGTH::::1 POTION:REGEN::::1'
      takeItems: true
      itemReward: 'ENCHANTMENT_TABLE:1'
      rewardText: 'Enchantment Table'
      moneyReward: 200
      expReward: 200
      permissionReward: ''
      repeatable: true
      repeatItemReward: 'DIAMOND:1'
      repeatRewardText: '1 diamond'
      repeatMoneyReward: 20
      repeatExpReward: 20
```
