### ISSUE TITLE
Cannot use datavalues in minishop

### ISSUE THREAD

**Issue by ShayBox** [tastybento/ASkyBlock-Bugs-N-Features#642]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2  

**Plugin version:**
3.0.8.1  

**What other plugins are you using? (do /plugins and paste here)**
PermissionsEx, WorldEdit, HungerKeeperPlus, Vault, ASkyBlock, Essentials, EssentialsChat  

**Description of issue. What happened?**
I cannot set `INK_SACK:4:1` in minishop.yml

**What do you think should happen?**
It should show the item as lapis, but this doesn't take in datavalues, `INK_SACK:4` or `INK_SACK 4`, the acidblock plugin wiki says `INK_SACK:4:1` but it doesn't work in askyblock

**Comment by tastybento** [comment]
Use this format:

```
   item2:
      material: INK_SACK
      description: Lapis
      extra: 4
      quantity: 1
      price: 100
      sellprice: 10
```
