### ISSUE TITLE
Entities limits does not seem to work

### ISSUE THREAD

**Issue by wasder** [tastybento/ASkyBlock-Bugs-N-Features#643]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** Paper 1.12.2 latest

**Plugin version:** V3.0.8.2

**Description of issue. What happened?**
Got this config:
```   
   # Animal breeding limits - if this is set to more than 0, then players will not be able
   # to breed more animals than that number on their island. A value of zero means no
   # limit. Note that animals will not be killed or reduced to this limit.
   # This WILL affect mobspawn blocks AND spawn egg use. Note that hearts will
   # still appear, but breeding will not happen.
   # Limit includes nether island if nether islands are active.
   breedinglimit: 0

   # General entity limiting
   # Use this section to limit how many entities can be added to an island.
   # 0 means the item will be blocked from placement completely.
   # Uncomment to set the limit. The numbers are just suggested values.
   # The limit is per-world, so a hopper limit of 30 means up to 30 in the overworld and
   # up to 30 in the nether.
   entitylimits:
     # Mobs, animals and other living entities
     #BAT: 10
     #BLAZE: 10
     #BOAT: 10
     #CAVE_SPIDER: 10
     CHICKEN: 25
     COW: 25
     #CREEPER: 10
     #DONKEY: 10
     #ENDERMAN: 10
     HORSE: 20
     #HUSK: 10
     #IRON_GOLEM: 10
     #LLAMA: 10
     #MAGMA_CUBE: 10
     #MULE: 10
     MUSHROOM_COW: 25
     OCELOT: 25
     PIG: 25
     #PIG_ZOMBIE: 10
     #POLAR_BEAR: 10
     RABBIT: 25
     SHEEP: 25
     #SKELETON: 10
     #SKELETON_HORSE: 10
     #SLIME: 20
     #SNOWMAN: 10
     #SPIDER: 10
     #SQUID: 10
     #STRAY: 10
     #WITCH: 10
     #WITHER: 10
     #WOLF: 10
     #ZOMBIE: 10
     #ZOMBIE_HORSE: 10
     #ZOMBIE_VILLAGER: 10     
     # These are the ONLY blocks that can be limited (because they are entities).
     BANNER: 100
     ITEM_FRAME: 200
     #FURNACE: 10
     #CHEST: 50
     TRAPPED_CHEST: 50
     #ENDER_CHEST: 1
     #JUKEBOX: 5
     #DISPENSER: 5
     #DROPPER: 5
     #SIGN: 10
     MOB_SPAWNER: 10
     #NOTE_BLOCK: 5
     ENCHANTMENT_TABLE: 10
     #BEACON: 12
     #SKULL: 50
     #DAYLIGHT_DETECTOR: 10
     HOPPER: 300
     #REDSTONE_COMPARATOR: 30
     #FLOWER_POT: 20
     #PAINTING: 5
     #ARMOR_STAND: 5
```
But somehow players are still be able to spawn more mobs. They are getting the message about the limit but mobs are still breeding.

![](https://i.imgur.com/SbC4wz0.png)
